"""one table changed

Revision ID: 4ca12ecfe9be
Revises: 886b7b493e9e
Create Date: 2021-03-18 16:05:02.545621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca12ecfe9be'
down_revision = '886b7b493e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('commented_user', sa.VARCHAR(length=20), nullable=True),
    sa.Column('body', sa.VARCHAR(length=60), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['addproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
