"""one table changed and one new table added

Revision ID: 747be824da16
Revises: 4ca12ecfe9be
Create Date: 2021-03-18 20:52:50.440286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747be824da16'
down_revision = '4ca12ecfe9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['addproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
