"""one table added

Revision ID: 886b7b493e9e
Revises: ac067c01cb3f
Create Date: 2021-03-18 15:21:24.305391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886b7b493e9e'
down_revision = 'ac067c01cb3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commented_user', sa.String(length=20), nullable=True),
    sa.Column('body', sa.String(length=60), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['addproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
