"""one table deleted

Revision ID: ac067c01cb3f
Revises: 242ae2dca2a4
Create Date: 2021-03-18 15:00:43.734134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac067c01cb3f'
down_revision = '242ae2dca2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=60), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('commented_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['commented_user_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['addproduct.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
